### ISSUE TITLE
Practical1_Chong

### ISSUE THREAD

**Issue by Chong03** [PU-SDS/git-and-github-training#2]
![image](https://user-images.githubusercontent.com/51225708/79186545-860f8600-7e4c-11ea-8f04-344c8fda0be0.png)

Is my git commit command works?

**Comment by farhansj** [comment]
you need to give a message to your commit. Usually, when you type git commit with the -m parameter, the terminal will open a text editor for you. But since in this case you use an emulator (MINGW64), then the text editor is not automatically opened. To solve this problem, you can add -m to the git commit command, e.g. git commit -m "initial commit"

**Comment by Chong03** [comment]
![image](https://user-images.githubusercontent.com/51225708/79186961-8d835f00-7e4d-11ea-8506-fdf8a9b95fa4.png)

**Comment by farhansj** [comment]
Perfect!
